# Generated by Django 6.0.6 on 2026-06-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userlogin',
        ),
    ]
